<?php

/**
 * Config file for the app
 * Usage:
 *   - $cfg = new Laminas\Config\Config( include WBSSAAS_PLUGIN_DIR . 'config/app.php' );
 *   - $cfg->api->base_url
 *   - $cfg->api->get( 'token', 'default_value' );
 * 
 * CLOUDFLARE
 * The token is generated by the user account dnd@integrity-asia.com
 * https://dash.cloudflare.com/profile/api-tokens
 * The token just allows to Edit DNS all zones
 * 
 * @since 2.2.0
 * 
 * @see https://github.com/laminas/laminas-config
 * 
 * @see https://docs.laminas.dev/laminas-config/
 */

return [
    'debug' => true,
    'env'   => 'staging', // staging | production
    'log'   => [
        'path' => WBSSAAS_PLUGIN_DIR . 'log/',
    ],
    'location' => [
        'staging' => [
            'name'  => 'Staging / Promox',
            'ip'    => '10.30.40.147',
            'fqdn'  => 'https://api.stg.phoenix-whistleblowing.com',
            'token' => '$2y$10$Dx6Hc7n0JvLxhSnmXmnl6uBtpJXL7Y6KA0rBfErur5N4jmdL4hIxW',
        ],
        'switzerland' => [
            'name'  => 'Switzerland',
            'ip'    => '195.15.223.129',
            'fqdn'  => 'https://api.phoenix-whistleblowing.com',
            'token' => '$2y$10$LyYHErs7CD3dSdVsnFhfJrTZ3Wnwa8szyGlaLKjxM1pTFhEVDEySy',
        ],
        'singapore' => [
            'name'  => 'Singapore',
            'ip'    => '15.235.140.90',
            'fqdn'  => 'https://api-sgp.phoenix-whistleblowing.com',
            'token' => '$2y$10$LyYHErs7CD3dSdVsnFhfJrTZ3Wnwa8szyGlaLKjxM1pTFhEVDEySy',
        ],
        'indonesia' => [
            'name'  => 'Indonesia',
            'ip'    => '103.216.188.146',
            'fqdn'  => 'https://api-jkt.phoenix-whistleblowing.com',
            'token' => '$2y$10$LyYHErs7CD3dSdVsnFhfJrTZ3Wnwa8szyGlaLKjxM1pTFhEVDEySy',
        ],
    ],
    'infomaniak' => [
        'token' => 'CfFZZLpb-pTmwamon_otd4w_YAZE2kLWlaEEkFADyvqdohMbMWuE-qHmUGnzfnZJcfm_973SWnla8s09', // https://manager.infomaniak.com/v3/802143/ng/accounts/token/list
        'inbox' => [
            'speak-up.link'             => '663264',
            'whistle-blowing.org'       => '710295',
            'whistleblowing.direct'     => '710293',
            'whistleblowinghotline.net' => '710290',
        ],
    ],
    'cloudflare' => [
        'token'                      => 'XSQFYGToVblI-bCnb11Es_V7ZAsyB-EnJgbWJeZt',
        '43210.org'                  => 'bb508053d007e4a52778ddf0abbabf42', 
        'phoenix-whistleblowing.com' => '552726850a077585b966699b532edead',
        'speak-up.link'              => 'fc0470c0c22fc871004d17e33c228085',
        'whistleblowing.direct'      => 'c79c55ff56e0170830ccc6e613f7596b',
        'whistleblowinghotline.net'  => 'b2c435a4aeef60da65423d89328e08c3',
        'whistle-blowing.org'        => 'be2826d232788707d7663114c2ae8b7a',
    ]
];
